name: 'Setup Node.js'
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.12.0'

    - name: Install dependencies
      shell: bash
      run: npm install -g yarn && yarn install --frozen-lockfile